### ISSUE TITLE
[Bug]: AttributeError: 'Namespace' object has no attribute 'use_zluda_dnn'

### ISSUE THREAD

**Issue by pinea00** [lshqqytiger/stable-diffusion-webui-amdgpu-forge#1]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

An error occurred during the installation and the webui could not be opened. Since updating to torch 2.3 (A1111 V1.93 use-zluda, using torch2.3 is completely normal)
torch2.2 can work normally, even if it shares VENV with A1111, it can also execute normally.

### Steps to reproduce the problem

1.git clone code
2.run webui-user.bat

### What should have happened?

Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-1.7.0
Commit hash: <none>
Total VRAM 8176 MB, total RAM 16222 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 6600 [ZLUDA] : native
VAE dtype: torch.bfloat16
Launching Web UI with arguments: --skip-torch-cuda-test --theme dark --api --autolaunch --ckpt-dir S:stablediffusion-webui/models/Stable-diffusion --hypernetwork-dir S:stablediffusion-webui/models/hypernetworks --embeddings-dir S:stablediffusion-webui/embeddings --lora-dir S:stablediffusion-webui/models/Lora
CUDA Stream Activated:  False
Using pytorch cross attention
ONNX: selected=CUDAExecutionProvider, available=['AzureExecutionProvider', 'CPUExecutionProvider']
Traceback (most recent call last):
  File "S:\stable-diffusion-webui-forge\launch.py", line 51, in <module>
    main()
  File "S:\stable-diffusion-webui-forge\launch.py", line 47, in main
    start()
  File "S:\stable-diffusion-webui-forge\modules\launch_utils.py", line 656, in start
    import webui
  File "S:\stable-diffusion-webui-forge\webui.py", line 19, in <module>
    initialize.imports()
  File "S:\stable-diffusion-webui-forge\modules\initialize.py", line 50, in imports
    shared_init.initialize()
  File "S:\stable-diffusion-webui-forge\modules\shared_init.py", line 66, in initialize
    initialize_zluda()
  File "S:\stable-diffusion-webui-forge\modules\zluda.py", line 34, in initialize_zluda
    torch.backends.cudnn.enabled = shared.cmd_opts.use_zluda_dnn
AttributeError: 'Namespace' object has no attribute 'use_zluda_dnn'

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

i can't start
GPU: RX6600
Zluda:3.7
OS:windows 10

### Console logs

```Shell
I can't start since I update to torch 2.3
```

**Comment by pinea00** [comment]
The author has fixed it~Thank you
