### ISSUE TITLE
SSLError: not enough data: cadata does not contain a certificate (_ssl.c:4015) When feching Extensions

### ISSUE THREAD

**Issue by VeteranXT** [lshqqytiger/stable-diffusion-webui-amdgpu-forge#18]
Title says it all

`Traceback (most recent call last):
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\modules\call_queue.py", line 76, in f
    res = list(func(*args, **kwargs))
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\modules\call_queue.py", line 55, in f
    res = func(*args, **kwargs)
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\modules\ui_extensions.py", line 411, in refresh_available_extensions
    with urllib.request.urlopen(url) as response:
  File "C:\Users\Vlada\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Vlada\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Users\Vlada\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\Vlada\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\Vlada\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\Vlada\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1317, in do_open
    h = http_class(host, timeout=req.timeout, **http_conn_args)
  File "C:\Users\Vlada\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1422, in __init__
    context = ssl._create_default_https_context()
  File "C:\Users\Vlada\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 771, in create_default_context
    context.load_default_certs(purpose)
  File "C:\Users\Vlada\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 592, in load_default_certs
    self._load_windows_store_certs(storename, purpose)
  File "C:\Users\Vlada\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 584, in _load_windows_store_certs
    self.load_verify_locations(cadata=certs)
ssl.SSLError: not enough data: cadata does not contain a certificate (_ssl.c:4015)
not enough data: cadata does not contain a certificate (_ssl.c:4015)`

**Comment by VeteranXT** [comment]
Found Fix.

**Comment by bladane** [comment]
Any hint -  how you fixed it?

**Comment by VeteranXT** [comment]
I saw you solved it. Our stupid county MUP SERBIA certificate is making this issue.

**Comment by bladane** [comment]
Yup - deleted all MUP SERBIA certs and installed only new ones - problem solved.
PUMPAAAJ! DINSTAAAJ!!!!
