### ISSUE TITLE
No module named 'gguf'

### ISSUE THREAD

**Issue by TheFerumn** [lshqqytiger/stable-diffusion-webui-amdgpu-forge#24]
Clean installation after new update. 
Commands: --directml --no-half-vae --no-half --loglevel debug
Can't launch SD with an error:

```
venv "C:\Stable Diffusion\new-forge\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-1.10.1
Commit hash: 09c889b628fbc3f33cf412383d10eb26baeb2a80
Installing requirements
2024-09-01 18:43:04 DEBUG [root] Installing put extensions here.txt
2024-09-01 18:43:04 DEBUG [root] Installing extra-options-section
2024-09-01 18:43:04 DEBUG [root] Installing forge_legacy_preprocessors
2024-09-01 18:43:05 DEBUG [root] Installing forge_preprocessor_inpaint
2024-09-01 18:43:05 DEBUG [root] Installing forge_preprocessor_marigold
2024-09-01 18:43:05 DEBUG [root] Installing forge_preprocessor_normalbae
2024-09-01 18:43:05 DEBUG [root] Installing forge_preprocessor_recolor
2024-09-01 18:43:05 DEBUG [root] Installing forge_preprocessor_reference
2024-09-01 18:43:05 DEBUG [root] Installing forge_preprocessor_revision
2024-09-01 18:43:05 DEBUG [root] Installing forge_preprocessor_tile
2024-09-01 18:43:05 DEBUG [root] Installing forge_space_animagine_xl_31
2024-09-01 18:43:05 DEBUG [root] Installing forge_space_birefnet
2024-09-01 18:43:05 DEBUG [root] Installing forge_space_example
2024-09-01 18:43:05 DEBUG [root] Installing forge_space_florence_2
2024-09-01 18:43:05 DEBUG [root] Installing forge_space_geowizard
2024-09-01 18:43:05 DEBUG [root] Installing forge_space_iclight
2024-09-01 18:43:05 DEBUG [root] Installing forge_space_idm_vton
2024-09-01 18:43:05 DEBUG [root] Installing forge_space_illusion_diffusion
2024-09-01 18:43:05 DEBUG [root] Installing forge_space_photo_maker_v2
2024-09-01 18:43:05 DEBUG [root] Installing forge_space_sapiens_normal
2024-09-01 18:43:05 DEBUG [root] Installing mobile
2024-09-01 18:43:05 DEBUG [root] Installing prompt-bracket-checker
2024-09-01 18:43:05 DEBUG [root] Installing ScuNET
2024-09-01 18:43:05 DEBUG [root] Installing sd_forge_controlllite
2024-09-01 18:43:05 DEBUG [root] Installing sd_forge_controlnet
2024-09-01 18:43:06 DEBUG [root] Installing sd_forge_dynamic_thresholding
2024-09-01 18:43:06 DEBUG [root] Installing sd_forge_fooocus_inpaint
2024-09-01 18:43:06 DEBUG [root] Installing sd_forge_freeu
2024-09-01 18:43:06 DEBUG [root] Installing sd_forge_ipadapter
2024-09-01 18:43:06 DEBUG [root] Installing sd_forge_kohya_hrfix
2024-09-01 18:43:06 DEBUG [root] Installing sd_forge_latent_modifier
2024-09-01 18:43:06 DEBUG [root] Installing sd_forge_lora
2024-09-01 18:43:06 DEBUG [root] Installing sd_forge_multidiffusion
2024-09-01 18:43:06 DEBUG [root] Installing sd_forge_neveroom
2024-09-01 18:43:06 DEBUG [root] Installing sd_forge_perturbed_attention
2024-09-01 18:43:06 DEBUG [root] Installing sd_forge_sag
2024-09-01 18:43:06 DEBUG [root] Installing sd_forge_stylealign
2024-09-01 18:43:06 DEBUG [root] Installing soft-inpainting
2024-09-01 18:43:06 DEBUG [root] Installing SwinIR
Traceback (most recent call last):
  File "C:\Stable Diffusion\new-forge\launch.py", line 54, in <module>
    main()
  File "C:\Stable Diffusion\new-forge\launch.py", line 42, in main
    prepare_environment()
  File "C:\Stable Diffusion\new-forge\modules\launch_utils.py", line 608, in prepare_environment
    from modules import devices
  File "C:\Stable Diffusion\new-forge\modules\devices.py", line 3, in <module>
    from backend import memory_management
  File "C:\Stable Diffusion\new-forge\backend\memory_management.py", line 10, in <module>
    from backend import stream, utils
  File "C:\Stable Diffusion\new-forge\backend\utils.py", line 1, in <module>
    import gguf
ModuleNotFoundError: No module named 'gguf'
```

**Comment by TheFerumn** [comment]
Passed error by adding

```
import sys
sys.path.append(r"C:\Stable Diffusion\new-forge\packages_3rdparty")
```
into the launch.py
