### ISSUE TITLE
Error loading Animatediff

### ISSUE THREAD

**Issue by thomashush** [lshqqytiger/stable-diffusion-webui-amdgpu-forge#28]
`*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "E:\automatic_forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\automatic_forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\automatic_forge\extensions\sd-webui-animatediff\scripts\animatediff.py", line 10, in <module>
        from scripts.animatediff_infv2v import AnimateDiffInfV2V
      File "E:\automatic_forge\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py", line 10, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "E:\automatic_forge\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 9, in <module>
        from motion_module import MotionWrapper, MotionModuleType
      File "E:\automatic_forge\extensions\sd-webui-animatediff\motion_module.py", line 10, in <module>
        from ldm.modules.attention import FeedForward
    ModuleNotFoundError: No module named 'ldm'`

Errors when trying to install Animatediff.

**Comment by Harbitos** [comment]
> download LDM folder from this link: https://github.com/CompVis/stable-diffusion and drop it into E:\automatic_forge

Of course, I spent 10 minutes trying to figure out exactly where to throw it, but I was able to.
It really helped!

However, my AnimateDiff interface displays only this:
Please help me if you know.
![Screenshot_1](https://github.com/user-attachments/assets/d701313b-b248-42fc-bf45-f23dc8d904e5)

A CLEARER INSTRUCTION ON HOW TO SOLVE THIS: 
Download "ldm" folder from this link: https://github.com/CompVis/stable-diffusion
And then you drop this folder into the stable diffusion folder itself.
Example: C:\stable-diffusion-webui-amdgpu-forge.

**Comment by TheFerumn** [comment]
> Of course, I spent 10 minutes trying to figure out exactly where to throw it, but I was able to. It really helped!
> 
> However, my AnimateDiff interface displays only this: Please help me if you know.

Is there any errors in console when you click on AnimateDiff tab ? If there is nothing then try with --loglevel debug command. If it will print some errors we can try to fix it.

**Comment by FREEWING-JP** [comment]
> download LDM folder from this link: https://github.com/CompVis/stable-diffusion and drop it into E:\automatic_forge

Thank you so much !
I was having trouble with the AnimateDiff tab not appearing in amdgpu-forge .
Your solution solved the problem !

**Comment by FREEWING-JP** [comment]
The first time it started up , the tab contents were normal, but the second time I started it up , the following error appeared .
> AttributeError: 'FakeInitialModel' object has no attribute 'is_sdxl'

not use xformers . (xformers: N/A)
The cause is unknown .
