### ISSUE TITLE
SD-FORGE-AMD. ModuleNotFoundError: No module named 'gguf'.    or    RuntimeError: Found no NVIDIA driver on your system.

### ISSUE THREAD

**Issue by Harbitos** [lshqqytiger/stable-diffusion-webui-amdgpu-forge#31]
I have a different situation, windows10, amd RX580 graphics card, Intel Xeon processor. The initial installation of stable-diffusion-webui-amdgpu-forge by lshqqytiger returns an error:

```
venv "C:\Users\user\Desktop\Stable Diffusion Forge AMD\stable-diffusion-webui-amdgpu-forge\venv\Scripts\Python.exe"
ROCm Toolkit 6.1 was found.
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-1.10.1
Commit hash: 412c2d800dcae4cee8a7466a1e9128cfbbc5bf26
Failed to load ZLUDA: Could not find module 'C:\Program Files\AMD\ROCm\6.1\bin\rocblas.dll' (or one of its dependencies). Try using the full path with constructor syntax.
Using CPU-only torch
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Stable Diffusion Forge AMD\stable-diffusion-webui-amdgpu-forge\launch.py", line 54, in <module>
    main()
  File "C:\Users\user\Desktop\Stable Diffusion Forge AMD\stable-diffusion-webui-amdgpu-forge\launch.py", line 42, in main
    prepare_environment()
  File "C:\Users\user\Desktop\Stable Diffusion Forge AMD\stable-diffusion-webui-amdgpu-forge\modules\launch_utils.py", line 608, in prepare_environment
    from modules import devices
  File "C:\Users\user\Desktop\Stable Diffusion Forge AMD\stable-diffusion-webui-amdgpu-forge\modules\devices.py", line 3, in <module>
    from backend import memory_management
  File "C:\Users\user\Desktop\Stable Diffusion Forge AMD\stable-diffusion-webui-amdgpu-forge\backend\memory_management.py", line 10, in <module>
    from backend import stream, utils
  File "C:\Users\user\Desktop\Stable Diffusion Forge AMD\stable-diffusion-webui-amdgpu-forge\backend\utils.py", line 1, in <module>
    import gguf
ModuleNotFoundError: No module named 'gguf'
To continue, press any key. . .

```

-------------------------------------------------------

But when added to launch.py
import sys
sys.path.append(r"C:\Stable Diffusion\new-forge\packages_3rdparty"),
gives me the following error:

```
venv "C:\Users\user\Desktop\Stable Diffusion Forge AMD\stable-diffusion-webui-amdgpu-forge\venv\Scripts\Python.exe"
ROCm Toolkit 6.1 was found.
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-1.10.1
Commit hash: 412c2d800dcae4cee8a7466a1e9128cfbbc5bf26
Failed to load ZLUDA: Could not find module 'C:\Program Files\AMD\ROCm\6.1\bin\rocblas.dll' (or one of its dependencies). Try using the full path with constructor syntax.
Using CPU-only torch
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Stable Diffusion Forge AMD\stable-diffusion-webui-amdgpu-forge\launch.py", line 57, in <module>
    main()
  File "C:\Users\user\Desktop\Stable Diffusion Forge AMD\stable-diffusion-webui-amdgpu-forge\launch.py", line 45, in main
    prepare_environment()
  File "C:\Users\user\Desktop\Stable Diffusion Forge AMD\stable-diffusion-webui-amdgpu-forge\modules\launch_utils.py", line 608, in prepare_environment
    from modules import devices
  File "C:\Users\user\Desktop\Stable Diffusion Forge AMD\stable-diffusion-webui-amdgpu-forge\modules\devices.py", line 3, in <module>
    from backend import memory_management
  File "C:\Users\user\Desktop\Stable Diffusion Forge AMD\stable-diffusion-webui-amdgpu-forge\backend\memory_management.py", line 133, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\user\Desktop\Stable Diffusion Forge AMD\stable-diffusion-webui-amdgpu-forge\backend\memory_management.py", line 100, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\user\Desktop\Stable Diffusion Forge AMD\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\cuda\__init__.py", line 778, in current_device
    _lazy_init()
  File "C:\Users\user\Desktop\Stable Diffusion Forge AMD\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\cuda\__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
To continue, press any key. . .
```

-------------------------------------------------------

Even when adding:
```
import logging
import traceback
logging.basicConfig(filename='error_log.txt', level=logging.DEBUG)
``` - leads to the same error as mentioned above about NVIDIA.

Adding `--use-directml` `--use-zluda` to COMMANDLINE_ARGS results in the same error with NVIDIA.
I read most of the issues on the Internet about gguf or NVIDIA, but I didn't find any useful information.
Please help me fix this.
I don't know much about programming, so if you need to add some code, write on which line and after that.
Screenshots are attached launch.py , in webui-user, nothing is written in COMMANDLINE_ARGS.
![Screenshot_1](https://github.com/user-attachments/assets/4e528af3-e68a-4337-a2df-223169c85fbe)
![Screenshot_2](https://github.com/user-attachments/assets/8f2522db-f3f8-4db2-bcbc-bfd6c57fded8)

**Comment by TheFerumn** [comment]
You fixed gguf problem but it looks like you haven't installed HIP SDK correctly.
![image](https://github.com/user-attachments/assets/f20a3cd3-96b9-48ea-876f-fab69c2eb9a4)

**Comment by TheFerumn** [comment]
If you want to use ZLUDA you have to remember your CPU must support PCIe™ atomics. For RX580 you probably need build your own RocblasLibs. 
Here is the link with whole guide:
https://github.com/vladmandic/automatic/wiki/ZLUDA

**Comment by VeteranXT** [comment]
Steps to fix: Go into `venv/scripts` open `CMD`. Type `activate  `then `pip install gguf`. Run.bat

**Comment by Harbitos** [comment]
> If you want to use ZLUDA you have to remember your CPU must support PCIe™ atomics. For RX580 you probably need build your own RocblasLibs. Here is the link with whole guide: https://github.com/vladmandic/automatic/wiki/ZLUDA
> 
> BTW: If you don't want to do this then you can just use `--directml` command

SD started working with directml, generated a couple of images, but also gave errors a couple of times: the first - nothing was written, restarting SD helped, the second - resource deadlock would occur:resource deadlock would occur, restarting helped too.

And which is better, ZLUDA or derectml? A friend told me that directml is more stable than ZLUDA.
If ZLUDA is better, then please explain as simply as possible how to install it, otherwise at one point it is difficult for me to create RocblasLibs libraries.

**Comment by TheFerumn** [comment]
As far as i know ZLUDA is faster and better but i can't test it myself. You have everything in the link i paste how to make ZLUDA work. There is nothing more to it you just need CPU supporting PCIe™ atomics. 

This is the whole guide:
![image](https://github.com/user-attachments/assets/bb3ac56f-deef-40cb-be94-073b86ca3147)

**Comment by TheFerumn** [comment]
> Steps to fix: Go into `venv/scripts` open `CMD`. Type `activate `then `pip install gguf`. Run.bat

He fixed it. I believe the method you mentioned doesn't work because Forge has its own integrated GGUF module but there is bug when its not visible. Downloading GGUF with `pip install gguf` will download wrong version

**Comment by Harbitos** [comment]
> As far as i know ZLUDA is faster and better but i can't test it myself. You have everything in the link i paste how to make ZLUDA work. There is nothing more to it you just need CPU supporting PCIe™ atomics.
> 
> This is the whole guide: ![image](https://private-user-images.githubusercontent.com/178197881/367333547-bb3ac56f-deef-40cb-be94-073b86ca3147.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNDI0ODEsIm5iZiI6MTcyNjI0MjE4MSwicGF0aCI6Ii8xNzgxOTc4ODEvMzY3MzMzNTQ3LWJiM2FjNTZmLWRlZWYtNDBjYi1iZTk0LTA3M2I4NmNhMzE0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QxNTQzMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZmYwMzNjMGFiZTJiNDQxNmEwNTIxZmQ5MWFjYmJjZmNkYzIyZjNiZTJkNjc3Y2U1MDY4OWExMDY3ZjA0YmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Un43HwtE-3VQb7ots3UYyZKG87LWVB3iykaUCP5CeF4)
> 
> RX580 is not on the list so you need to build your own RocblasLibs BUT i saw once somewhere ppl already made libs for RX580 so if you will look for it in google you should be able to find

Drop the link, I can't find it.

**Comment by TheFerumn** [comment]
> Drop the link, I can't find it.

I don't want to be mean to you or anything but if you can't find the link from few comments above which you even quoted then just give up and use DirectML :D

**Comment by ElusiveT** [comment]
> Steps to fix: Go into `venv/scripts` open `CMD`. Type `activate `then `pip install gguf`. Run.bat

i had the `ModuleNotFoundError: No module named 'gguf'` error. i edited launch.py as in the original comment, then i did what this comment said, and that fixed it
