### ISSUE TITLE
[BUG] ControlNet Reference with DirectML ?

### ISSUE THREAD

**Issue by TheFerumn** [lshqqytiger/stable-diffusion-webui-amdgpu-forge#35]
Trying to use ControlNet Reference with `--directml`

```
*** Error running process_before_every_sampling: C:\Stable-Diffusion\new-forge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Stable-Diffusion\new-forge\modules\scripts.py", line 892, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "C:\Stable-Diffusion\new-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\Stable-Diffusion\new-forge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 561, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
      File "C:\Stable-Diffusion\new-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\Stable-Diffusion\new-forge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 503, in process_unit_before_every_sampling
        cond, mask = params.preprocessor.process_before_every_sampling(p, cond, mask, *args, **kwargs)
      File "C:\Stable-Diffusion\new-forge\extensions-builtin\forge_preprocessor_reference\scripts\forge_reference.py", line 67, in process_before_every_sampling
        gen_cpu = torch.Generator().manual_seed(gen_seed)
      File "C:\Stable-Diffusion\new-forge\modules\sd_hijack_utils.py", line 22, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "C:\Stable-Diffusion\new-forge\modules\sd_hijack_utils.py", line 33, in __call__
        if not self.__cond_func or self.__cond_func(self.__orig_func, *args, **kwargs):
    TypeError: directml_do_hijack.<locals>.<lambda>() missing 1 required positional argument: 'device'
```

**Comment by TheFerumn** [comment]
Temporary fix:
Changed line 67 of forge_reference.py
Into 
`gen_cpu = torch.Generator(device='dml').manual_seed(gen_seed)`

ControlNet Reference works but only when you set 512x512 resolution for generated image. Looks like resolution of uploaded image doesn't matter.

Using any other resolution gives an error:
```
  File "C:\Stable-Diffusion\new-forge\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "C:\Stable-Diffusion\new-forge\modules\txt2img.py", line 123, in txt2img_function
    processed = processing.process_images(p)
  File "C:\Stable-Diffusion\new-forge\modules\processing.py", line 818, in process_images
    res = process_images_inner(p)
  File "C:\Stable-Diffusion\new-forge\modules\processing.py", line 1053, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "C:\Stable-Diffusion\new-forge\modules\processing.py", line 1430, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "C:\Stable-Diffusion\new-forge\modules\sd_samplers_kdiffusion.py", line 240, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\Stable-Diffusion\new-forge\modules\sd_samplers_common.py", line 272, in launch_sampling
    return func()
  File "C:\Stable-Diffusion\new-forge\modules\sd_samplers_kdiffusion.py", line 240, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\Stable-Diffusion\new-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Stable-Diffusion\new-forge\k_diffusion\sampling.py", line 146, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\Stable-Diffusion\new-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Stable-Diffusion\new-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Stable-Diffusion\new-forge\modules\sd_samplers_cfg_denoiser.py", line 199, in forward
    denoised, cond_pred, uncond_pred = sampling_function(self, denoiser_params=denoiser_params, cond_scale=cond_scale, cond_composition=cond_composition)
  File "C:\Stable-Diffusion\new-forge\backend\sampling\sampling_function.py", line 362, in sampling_function
    denoised, cond_pred, uncond_pred = sampling_function_inner(model, x, timestep, uncond, cond, cond_scale, model_options, seed, return_full=True)
  File "C:\Stable-Diffusion\new-forge\backend\sampling\sampling_function.py", line 303, in sampling_function_inner
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "C:\Stable-Diffusion\new-forge\backend\sampling\sampling_function.py", line 273, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "C:\Stable-Diffusion\new-forge\backend\modules\k_model.py", line 45, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "C:\Stable-Diffusion\new-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Stable-Diffusion\new-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Stable-Diffusion\new-forge\backend\nn\unet.py", line 713, in forward
    h = module(h, emb, context, transformer_options)
  File "C:\Stable-Diffusion\new-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Stable-Diffusion\new-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Stable-Diffusion\new-forge\backend\nn\unet.py", line 83, in forward
    x = layer(x, context, transformer_options)
  File "C:\Stable-Diffusion\new-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Stable-Diffusion\new-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Stable-Diffusion\new-forge\backend\nn\unet.py", line 321, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)
  File "C:\Stable-Diffusion\new-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Stable-Diffusion\new-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Stable-Diffusion\new-forge\backend\nn\unet.py", line 181, in forward
    return checkpoint(self._forward, (x, context, transformer_options), None, self.checkpoint)
  File "C:\Stable-Diffusion\new-forge\backend\nn\unet.py", line 12, in checkpoint
    return f(*args)
  File "C:\Stable-Diffusion\new-forge\backend\nn\unet.py", line 232, in _forward
    n = attn1_replace_patch[block_attn1](n, context_attn1, value_attn1, extra_options)
  File "C:\Stable-Diffusion\new-forge\extensions-builtin\forge_preprocessor_reference\scripts\forge_reference.py", line 175, in attn1_proc
    o_uc = o_uc_weak + (o_uc_strong - o_uc_weak) * style_fidelity
RuntimeError: The size of tensor a (0) must match the size of tensor b (320) at non-singleton dimension 2
The size of tensor a (0) must match the size of tensor b (320) at non-singleton dimension 2
```

Also tried to change device to CPU but same error with other dimensions than 512x512

**Comment by lshqqytiger** [comment]
Fixed.
