### ISSUE TITLE
RuntimeError: CUDA error: operation not supported ; Failed to load ZLUDA: list index out of range

### ISSUE THREAD

**Issue by jdw-mis** [lshqqytiger/stable-diffusion-webui-amdgpu-forge#36]
OS: Windows 11 Build 22631
GPU: 6700 XT
Driver: 24.10.16 (Pro Edition)
ROCm/HIP: both 5.7.1 and 6.1.2
Python: 3.10.6
I have already replaced the ROCm libraries for both ROCm versions with the gtx1031 libraries as detailed here: https://github.com/brknsoul/ROCmLibs/wiki/Installing-Forge%E2%80%90Zluda

WebUI launches, allows for full input, but when attempting to generate an image with any model it fails with the message:
```
RuntimeError: CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
Notably, prior in the log I've noticed the following lines:
```
fatal: No names found, cannot describe anything.
Failed to load ZLUDA: list index out of range
Using CPU-only torch
2024-09-21 16:59:18 DEBUG [PIL.Image] Image: failed to import FpxImagePlugin: No module named 'olefile'
2024-09-21 16:59:18 DEBUG [PIL.Image] Image: failed to import MicImagePlugin: No module named 'olefile'
ZLUDA device failed to pass basic operation test: index=0, device_name=AMD Radeon RX 6700 XT [ZLUDA]
```
I have attempted to install ZLUDA manually, it changed nothing. Same with deleting one or the other ROCm version paths. I think its just not loading ZLUDA for some incomprehensible reason.

<details>
<summary>Full Log</summary>

```
venv "C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge\venv\Scripts\Python.exe"
WARNING: ZLUDA works best with SD.Next. Please consider migrating to SD.Next.
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-1.10.1
Commit hash: 2e4a9d6f849294b4f2988d8e7f93bf10259e52cb
Using ZLUDA in C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge\.zluda
Failed to load ZLUDA: list index out of range
Using CPU-only torch
2024-09-21 16:58:58 DEBUG [root] Installing put extensions here.txt
2024-09-21 16:58:58 DEBUG [root] Installing extra-options-section
2024-09-21 16:58:58 DEBUG [root] Installing forge_legacy_preprocessors
2024-09-21 16:58:58 DEBUG [root] Installing forge_preprocessor_inpaint
2024-09-21 16:58:58 DEBUG [root] Installing forge_preprocessor_marigold
2024-09-21 16:58:58 DEBUG [root] Installing forge_preprocessor_normalbae
2024-09-21 16:58:58 DEBUG [root] Installing forge_preprocessor_recolor
2024-09-21 16:58:58 DEBUG [root] Installing forge_preprocessor_reference
2024-09-21 16:58:58 DEBUG [root] Installing forge_preprocessor_revision
2024-09-21 16:58:58 DEBUG [root] Installing forge_preprocessor_tile
2024-09-21 16:58:58 DEBUG [root] Installing forge_space_animagine_xl_31
2024-09-21 16:58:58 DEBUG [root] Installing forge_space_birefnet
2024-09-21 16:58:58 DEBUG [root] Installing forge_space_example
2024-09-21 16:58:58 DEBUG [root] Installing forge_space_florence_2
2024-09-21 16:58:58 DEBUG [root] Installing forge_space_geowizard
2024-09-21 16:58:58 DEBUG [root] Installing forge_space_iclight
2024-09-21 16:58:58 DEBUG [root] Installing forge_space_idm_vton
2024-09-21 16:58:58 DEBUG [root] Installing forge_space_illusion_diffusion
2024-09-21 16:58:58 DEBUG [root] Installing forge_space_photo_maker_v2
2024-09-21 16:58:58 DEBUG [root] Installing forge_space_sapiens_normal
2024-09-21 16:58:58 DEBUG [root] Installing mobile
2024-09-21 16:58:58 DEBUG [root] Installing prompt-bracket-checker
2024-09-21 16:58:58 DEBUG [root] Installing ScuNET
2024-09-21 16:58:58 DEBUG [root] Installing sd_forge_controlllite
2024-09-21 16:58:58 DEBUG [root] Installing sd_forge_controlnet
2024-09-21 16:58:59 DEBUG [root] Installing sd_forge_dynamic_thresholding
2024-09-21 16:58:59 DEBUG [root] Installing sd_forge_fooocus_inpaint
2024-09-21 16:58:59 DEBUG [root] Installing sd_forge_freeu
2024-09-21 16:58:59 DEBUG [root] Installing sd_forge_ipadapter
2024-09-21 16:58:59 DEBUG [root] Installing sd_forge_kohya_hrfix
2024-09-21 16:58:59 DEBUG [root] Installing sd_forge_latent_modifier
2024-09-21 16:58:59 DEBUG [root] Installing sd_forge_lora
2024-09-21 16:58:59 DEBUG [root] Installing sd_forge_multidiffusion
2024-09-21 16:58:59 DEBUG [root] Installing sd_forge_neveroom
2024-09-21 16:58:59 DEBUG [root] Installing sd_forge_perturbed_attention
2024-09-21 16:58:59 DEBUG [root] Installing sd_forge_sag
2024-09-21 16:58:59 DEBUG [root] Installing sd_forge_stylealign
2024-09-21 16:58:59 DEBUG [root] Installing soft-inpainting
2024-09-21 16:58:59 DEBUG [root] Installing SwinIR
Launching Web UI with arguments: --theme dark --use-zluda --loglevel debug
Total VRAM 12272 MB, total RAM 32621 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 6700 XT [ZLUDA] : native
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False
2024-09-21 16:59:11 DEBUG [httpx] load_ssl_context verify=True cert=None trust_env=True http2=False
2024-09-21 16:59:11 DEBUG [httpx] load_verify_locations cafile='C:\\stable-diffusion-webui\\stable-diffusion-webui-amdgpu-forge\\venv\\lib\\site-packages\\certifi\\cacert.pem'
2024-09-21 16:59:11 DEBUG [httpx] load_ssl_context verify=True cert=None trust_env=True http2=False
2024-09-21 16:59:11 DEBUG [httpx] load_verify_locations cafile='C:\\stable-diffusion-webui\\stable-diffusion-webui-amdgpu-forge\\venv\\lib\\site-packages\\certifi\\cacert.pem'
2024-09-21 16:59:11 DEBUG [httpx] load_ssl_context verify=True cert=None trust_env=True http2=False
2024-09-21 16:59:11 DEBUG [httpx] load_verify_locations cafile='C:\\stable-diffusion-webui\\stable-diffusion-webui-amdgpu-forge\\venv\\lib\\site-packages\\certifi\\cacert.pem'
2024-09-21 16:59:11 DEBUG [bitsandbytes.cextension] Loading bitsandbytes native library from: C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll
Using pytorch cross attention
Using pytorch attention for VAE
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing BlpImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing BmpImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing BufrStubImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing CurImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing DcxImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing DdsImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing EpsImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing FitsImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing FitsStubImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing FliImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing FpxImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Image: failed to import FpxImagePlugin: No module named 'olefile'
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing FtexImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing GbrImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing GifImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing GribStubImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing Hdf5StubImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing IcnsImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing IcoImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing ImImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing ImtImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing IptcImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing JpegImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing Jpeg2KImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing McIdasImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing MicImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Image: failed to import MicImagePlugin: No module named 'olefile'
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing MpegImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing MpoImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing MspImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing PalmImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing PcdImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing PcxImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing PdfImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing PixarImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing PngImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing PpmImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing PsdImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing QoiImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing SgiImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing SpiderImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing SunImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing TgaImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing TiffImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing WebPImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing WmfImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing XbmImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing XpmImagePlugin
2024-09-21 16:59:18 DEBUG [PIL.Image] Importing XVThumbImagePlugin
2024-09-21 16:59:23 DEBUG [matplotlib] matplotlib data path: C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\matplotlib\mpl-data
2024-09-21 16:59:23 DEBUG [matplotlib] CONFIGDIR=C:\Users\MEDIUM_MK_5_0\.matplotlib
2024-09-21 16:59:23 DEBUG [matplotlib] interactive is False
2024-09-21 16:59:23 DEBUG [matplotlib] platform is win32
2024-09-21 16:59:23 DEBUG [matplotlib] CACHEDIR=C:\Users\MEDIUM_MK_5_0\.matplotlib
2024-09-21 16:59:23 DEBUG [matplotlib.font_manager] Using fontManager instance from C:\Users\MEDIUM_MK_5_0\.matplotlib\fontlist-v390.json
2024-09-21 16:59:24 DEBUG [git.cmd] Popen(['git', 'version'], cwd=C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge, universal_newlines=False, shell=None, istream=None)
2024-09-21 16:59:24 DEBUG [git.cmd] Popen(['git', 'version'], cwd=C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge, universal_newlines=False, shell=None, istream=None)
ONNX: version=1.19.2 provider=CPUExecutionProvider, available=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
ZLUDA device failed to pass basic operation test: index=0, device_name=AMD Radeon RX 6700 XT [ZLUDA]
CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

ControlNet preprocessor location: C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge\models\ControlNetPreprocessor
2024-09-21 16:59:30 DEBUG [asyncio] Using selector: SelectSelector
2024-09-21 16:59:31,709 - ControlNet - INFO - ControlNet UI callback registered.
Model selected: {'checkpoint_info': {'filename': 'C:\\stable-diffusion-webui\\stable-diffusion-webui-amdgpu-forge\\models\\Stable-diffusion\\AbyssOrangeMix2_nsfw.safetensors', 'hash': 'a87fd7da'}, 'additional_modules': [], 'unet_storage_dtype': None}
Using online LoRAs in FP16: False
2024-09-21 16:59:33 DEBUG [asyncio] Using selector: SelectSelector
Running on local URL:  http://127.0.0.1:7860
2024-09-21 16:59:34 DEBUG [httpx] load_ssl_context verify=None cert=None trust_env=True http2=False
2024-09-21 16:59:34 INFO [httpx] HTTP Request: GET http://127.0.0.1:7860/startup-events "HTTP/1.1 200 OK"
2024-09-21 16:59:34 DEBUG [httpx] load_ssl_context verify=False cert=None trust_env=True http2=False
2024-09-21 16:59:34 INFO [httpx] HTTP Request: HEAD http://127.0.0.1:7860/ "HTTP/1.1 200 OK"

To create a public link, set `share=True` in `launch()`.
Startup time: 39.6s (prepare environment: 4.5s, import torch: 25.3s, initialize shared: 2.7s, other imports: 0.1s, load scripts: 2.8s, create ui: 2.8s, gradio launch: 1.6s).
2024-09-21 16:59:38 DEBUG [matplotlib.pyplot] Loaded backend tkagg version 8.6.
2024-09-21 16:59:38 DEBUG [matplotlib.pyplot] Loaded backend agg version v2.2.
2024-09-21 16:59:38 DEBUG [matplotlib.pyplot] Loaded backend tkagg version 8.6.
2024-09-21 16:59:38 DEBUG [matplotlib.pyplot] Loaded backend agg version v2.2.
2024-09-21 16:59:38 DEBUG [matplotlib.pyplot] Loaded backend tkagg version 8.6.
2024-09-21 16:59:38 DEBUG [matplotlib.pyplot] Loaded backend agg version v2.2.
Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}
[GPU Setting] You will use 91.66% GPU memory (11248.00 MB) to load weights, and use 8.34% GPU memory (1024.00 MB) to do matrix computation.
2024-09-21 16:59:38 DEBUG [git.cmd] Popen(['git', 'remote', 'get-url', '--all', 'origin'], cwd=C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge, universal_newlines=False, shell=None, istream=None)
2024-09-21 16:59:38 DEBUG [git.cmd] Popen(['git', 'cat-file', '--batch-check'], cwd=C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge, universal_newlines=False, shell=None, istream=<valid stream>)
2024-09-21 16:59:38 DEBUG [git.cmd] Popen(['git', 'cat-file', '--batch'], cwd=C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge, universal_newlines=False, shell=None, istream=<valid stream>)
2024-09-21 16:59:38 DEBUG [git.cmd] Popen(['git', 'remote', 'get-url', '--all', 'origin'], cwd=C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge, universal_newlines=False, shell=None, istream=None)
2024-09-21 16:59:39 DEBUG [git.cmd] Popen(['git', 'cat-file', '--batch-check'], cwd=C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge, universal_newlines=False, shell=None, istream=<valid stream>)
2024-09-21 16:59:39 DEBUG [git.cmd] Popen(['git', 'cat-file', '--batch'], cwd=C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge, universal_newlines=False, shell=None, istream=<valid stream>)
2024-09-21 17:00:19 DEBUG [multipart.multipart] Calling on_part_begin with no data
2024-09-21 17:00:19 DEBUG [multipart.multipart] Calling on_header_field with data[42:61]
2024-09-21 17:00:19 DEBUG [multipart.multipart] Calling on_header_value with data[63:119]
2024-09-21 17:00:19 DEBUG [multipart.multipart] Calling on_header_end with no data
2024-09-21 17:00:19 DEBUG [multipart.multipart] Calling on_header_field with data[121:133]
2024-09-21 17:00:19 DEBUG [multipart.multipart] Calling on_header_value with data[135:144]
2024-09-21 17:00:19 DEBUG [multipart.multipart] Calling on_header_end with no data
2024-09-21 17:00:19 DEBUG [multipart.multipart] Calling on_headers_finished with no data
2024-09-21 17:00:19 DEBUG [multipart.multipart] Calling on_part_data with data[148:152]
2024-09-21 17:00:19 DEBUG [multipart.multipart] Calling on_part_data with data[0:2]
2024-09-21 17:00:19 DEBUG [multipart.multipart] Calling on_part_data with data[154:32768]
2024-09-21 17:00:19 DEBUG [multipart.multipart] Calling on_part_data with data[0:83824]
2024-09-21 17:00:19 DEBUG [multipart.multipart] Calling on_part_data with data[0:1]
2024-09-21 17:00:19 DEBUG [multipart.multipart] Calling on_part_data with data[83825:262144]
2024-09-21 17:00:19 DEBUG [multipart.multipart] Calling on_part_data with data[0:34493]
2024-09-21 17:00:19 DEBUG [multipart.multipart] Calling on_part_data with data[0:1]
2024-09-21 17:00:19 DEBUG [multipart.multipart] Calling on_part_data with data[34494:36008]
2024-09-21 17:00:19 DEBUG [multipart.multipart] Calling on_part_data with data[0:1]
2024-09-21 17:00:19 DEBUG [multipart.multipart] Calling on_part_data with data[36009:64741]
2024-09-21 17:00:19 DEBUG [multipart.multipart] Calling on_part_data with data[0:1]
2024-09-21 17:00:19 DEBUG [multipart.multipart] Calling on_part_data with data[64742:244716]
2024-09-21 17:00:19 DEBUG [multipart.multipart] Calling on_part_end with no data
2024-09-21 17:00:19 DEBUG [multipart.multipart] Calling on_end with no data
2024-09-21 17:00:19 DEBUG [PIL.PngImagePlugin] STREAM b'IHDR' 16 13
2024-09-21 17:00:19 DEBUG [PIL.PngImagePlugin] STREAM b'tEXt' 41 873
2024-09-21 17:00:19 DEBUG [PIL.PngImagePlugin] STREAM b'IDAT' 926 65536
2024-09-21 17:00:21 INFO [modules.shared_state] Starting job task(7wz5ssxykbpqt06)
Exception in thread MemMon:
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge\modules\memmon.py", line 43, in run
    torch.cuda.reset_peak_memory_stats()
  File "C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\cuda\memory.py", line 309, in reset_peak_memory_stats
    return torch._C._cuda_resetPeakMemoryStats(device)
RuntimeError: invalid argument to reset_peak_memory_stats
Loading Model: {'checkpoint_info': {'filename': 'C:\\stable-diffusion-webui\\stable-diffusion-webui-amdgpu-forge\\models\\Stable-diffusion\\AbyssOrangeMix2_nsfw.safetensors', 'hash': 'a87fd7da'}, 'additional_modules': [], 'unet_storage_dtype': None}
[Unload] Trying to free all memory for cuda:0 with 0 models keep loaded ... Done.
StateDict Keys: {'unet': 686, 'vae': 248, 'text_encoder': 197, 'ignore': 0}
C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
K-Model Created: {'storage_dtype': torch.float16, 'computation_dtype': torch.float16}
Model loaded in 1.4s (unload existing model: 0.2s, forge model load: 1.2s).
[Unload] Trying to free 1329.14 MB for cuda:0 with 0 models keep loaded ... Done.
[Memory Management] Target: JointTextEncoder, Free GPU: 10704.50 MB, Model Require: 234.72 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: 9445.78 MB, All loaded to GPU.
Moving model(s) has taken 0.40 seconds
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge\modules\txt2img.py", line 123, in txt2img_function
    processed = processing.process_images(p)
  File "C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge\modules\processing.py", line 818, in process_images
    res = process_images_inner(p)
  File "C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge\modules\processing.py", line 1023, in process_images_inner
    p.setup_conds()
  File "C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge\modules\processing.py", line 1619, in setup_conds
    super().setup_conds()
  File "C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge\modules\processing.py", line 501, in setup_conds
    self.uc = self.get_conds_with_caching(prompt_parser.get_learned_conditioning, negative_prompts, total_steps, [self.cached_uc], self.extra_network_data)
  File "C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge\modules\processing.py", line 472, in get_conds_with_caching
    cache[1] = function(shared.sd_model, required_prompts, steps, hires_steps, shared.opts.use_old_scheduling)
  File "C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge\modules\prompt_parser.py", line 189, in get_learned_conditioning
    conds = model.get_learned_conditioning(texts)
  File "C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge\backend\diffusion_engine\sd15.py", line 63, in get_learned_conditioning
    cond = self.text_processing_engine(prompt)
  File "C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge\backend\text_processing\classic_engine.py", line 268, in __call__
    z = self.process_tokens(tokens, multipliers)
  File "C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge\backend\text_processing\classic_engine.py", line 301, in process_tokens
    z = self.encode_with_transformers(tokens)
  File "C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge\backend\text_processing\classic_engine.py", line 126, in encode_with_transformers
    self.text_encoder.transformer.text_model.embeddings.position_embedding = self.text_encoder.transformer.text_model.embeddings.position_embedding.to(dtype=torch.float32)
  File "C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1173, in to
    return self._apply(convert)
  File "C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 804, in _apply
    param_applied = fn(param)
  File "C:\stable-diffusion-webui\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1159, in convert
    return t.to(
RuntimeError: CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2024-09-21 17:00:23 INFO [modules.shared_state] Ending job task(7wz5ssxykbpqt06) (1.91 seconds)

```

</details>

**Comment by TheFerumn** [comment]
Definitely Zluda error. Try to uninstall HIP SDK 6.1.2, reinstall HIP SDK 5.7.1 put optimized rocmlibs again and make sure you put in correct folder. Then before launching Forge delete Venv folder. If it won't work you might try to delete venv folder again and change command into `--zluda`  i am not sure if `--use-zluda` still works correctly but i was installing only on `--zluda` command without any issues

**Comment by TheFerumn** [comment]
I was going to ask if your folder is added to PATH but i was like "naaah it was added automatically when i was testing zluda". Kind of funny how on 1 PC it adds itself but on other it doesn't. Windows is like a lottery :D
