### ISSUE TITLE
[WinError 127] The specified procedure could not be found.

### ISSUE THREAD

**Issue by fasero1** [lshqqytiger/stable-diffusion-webui-amdgpu-forge#39]
Hello, does anybody know how to fix this issue? Win11. RX 7800 XT
Traceback (most recent call last):
  File "C:\Stable\stable-diffusion-webui-amdgpu-forge\launch.py", line 54, in <module>
    main()
  File "C:\Stable\stable-diffusion-webui-amdgpu-forge\launch.py", line 50, in main
    start()
  File "C:\Stable\stable-diffusion-webui-amdgpu-forge\modules\launch_utils.py", line 655, in start
    import webui
  File "C:\Stable\stable-diffusion-webui-amdgpu-forge\webui.py", line 17, in <module>
    initialize_forge()
  File "C:\Stable\stable-diffusion-webui-amdgpu-forge\modules_forge\initialization.py", line 58, in initialize_forge
    from backend import memory_management
  File "C:\Stable\stable-diffusion-webui-amdgpu-forge\backend\memory_management.py", line 6, in <module>
    import torch
  File "C:\Stable\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\__init__.py", line 132, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Stable\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.

**Comment by TheFerumn** [comment]
Need more info. Is it clean installation ? Which version of Torch ? I don't even have torch_init_.py in site-packages folder in my version.

**Comment by fasero1** [comment]
Thanks for checking, jus t fix this issue. Yes it was clean installation. Just deinstall old Zluda and delete it from system path, then reinstall SD. You can close this issue for now.
