### ISSUE TITLE
05.10.2024 The image with the snowpony_v10 model is corrupted.

### ISSUE THREAD

**Issue by Harbitos** [lshqqytiger/stable-diffusion-webui-amdgpu-forge#41]
![Screenshot_2](https://github.com/user-attachments/assets/3e3c2e4c-ef97-495b-82e7-a06cdb3df2f7)

I say right away, all other models are working fine.
Up to 97% of the generation, the image looks quite normal and saturated, and as a result it became pale and with white dots.
I tried to install the "prevent-artifact" extension, the check mark on "Prevent Stability-AI's ldm/sgm modules from printing noise to console" was already there.

(Information about my PC and what I tried to do is written at the end of this issue)

---------------------------------------------
I pay attention to the line in the console:
`WARNING: no ROCm agent was found!` is this normal? I didn't have it once or it was written `Found ROCm agent gfx803`.

I also pay attention to the paragraph:
`Error loading script: pa.py ...` - this definitely hasn't happened before.

```
venv "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\venv\Scripts\Python.exe"
WARNING: ZLUDA works best with SD.Next. Please consider migrating to SD.Next.
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-1.10.1
Commit hash: 545cb6bf1187a11475ce2b28b3f7f99938cddf3d
Using ZLUDA in C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\.zluda
WARNING: no ROCm agent was found!
Launching Web UI with arguments: --use-zluda --no-half-vae --no-half --upcast-sampling --precision full --theme dark --skip-version-check
You are using PyTorch below version 2.3. Some optimizations will be disabled.
Total VRAM 8192 MB, total RAM 16328 MB
pytorch version: 2.2.1+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 580 2048SP [ZLUDA] : native
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False
Using pytorch cross attention
Using pytorch attention for VAE
ONNX: version=1.19.2 provider=CPUExecutionProvider, available=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
ControlNet preprocessor location: C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\models\ControlNetPreprocessor
*** Error loading script: pa.py
    Traceback (most recent call last):
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-webui-prevent-artifact\scripts\pa.py", line 55, in <module>
        sd_hijack_clip.FrozenCLIPEmbedderWithCustomWordsBase.process_tokens = process_tokens
    AttributeError: module 'modules.sd_hijack_clip' has no attribute 'FrozenCLIPEmbedderWithCustomWordsBase'

---
2024-10-05 13:59:02,946 - ControlNet - INFO - ControlNet UI callback registered.
Model selected: {'checkpoint_info': {'filename': 'C:\\Stable Diffusion\\stable-diffusion-webui-amdgpu-forge\\models\\Stable-diffusion\\snowpony_v10.safetensors', 'hash': '7a851477'}, 'additional_modules': [], 'unet_storage_dtype': None}
Using online LoRAs in FP16: False
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 19.5s (prepare environment: 1.2s, import torch: 9.2s, initialize shared: 1.0s, load scripts: 2.8s, initialize google blockly: 0.2s, create ui: 3.2s, gradio launch: 1.7s).
Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}
[GPU Setting] You will use 87.50% GPU memory (7168.00 MB) to load weights, and use 12.50% GPU memory (1024.00 MB) to do matrix computation.
Loading Model: {'checkpoint_info': {'filename': 'C:\\Stable Diffusion\\stable-diffusion-webui-amdgpu-forge\\models\\Stable-diffusion\\snowpony_v10.safetensors', 'hash': '7a851477'}, 'additional_modules': [], 'unet_storage_dtype': None}
[Unload] Trying to free all memory for cuda:0 with 0 models keep loaded ... Done.
StateDict Keys: {'unet': 1680, 'vae': 248, 'text_encoder': 197, 'text_encoder_2': 518, 'ignore': 0}
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
K-Model Created: {'storage_dtype': torch.float16, 'computation_dtype': torch.float16}
Model loaded in 1.4s (unload existing model: 0.3s, forge model load: 1.2s).
[Unload] Trying to free 3051.58 MB for cuda:0 with 0 models keep loaded ... Done.
[Memory Management] Target: JointTextEncoder, Free GPU: 7347.49 MB, Model Require: 1559.68 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: 4763.81 MB, All loaded to GPU.
Moving model(s) has taken 3.74 seconds
[Unload] Trying to free 1024.00 MB for cuda:0 with 1 models keep loaded ... Current free memory is 5535.76 MB ... Done.
[Unload] Trying to free 7390.16 MB for cuda:0 with 0 models keep loaded ... Current free memory is 5568.69 MB ... Unload model JointTextEncoder Done.
[Memory Management] Target: KModel, Free GPU: 7315.67 MB, Model Require: 4897.05 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: 1394.62 MB, All loaded to GPU.
Moving model(s) has taken 17.44 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [01:08<00:00,  2.29s/it]
[Unload] Trying to free 1296.42 MB for cuda:0 with 0 models keep loaded ... Current free memory is 2240.49 MB ... Done.
[Memory Management] Target: IntegratedAutoencoderKL, Free GPU: 2240.49 MB, Model Require: 159.56 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: 1056.93 MB, All loaded to GPU.
Moving model(s) has taken 0.09 seconds
Total progress: 100%|██████████████████████████████████████████████████████████████████| 30/30 [01:11<00:00,  2.39s/it]
Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}11<00:00,  2.29s/it]
[GPU Setting] You will use 87.50% GPU memory (7168.00 MB) to load weights, and use 12.50% GPU memory (1024.00 MB) to do matrix computation.
[Unload] Trying to free all memory for cuda:0 with 0 models keep loaded ... Current free memory is 1280.00 MB ... Unload model KModel Current free memory is 6277.86 MB ... Unload model IntegratedAutoencoderKL Done.
[Unload] Trying to free 3302.87 MB for cuda:0 with 0 models keep loaded ... Done.
[Memory Management] Target: JointTextEncoder, Free GPU: 5931.52 MB, Model Require: 1752.98 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: 3154.54 MB, All loaded to GPU.
Moving model(s) has taken 0.65 seconds
[Unload] Trying to free 1024.00 MB for cuda:0 with 1 models keep loaded ... Current free memory is 4133.21 MB ... Done.
[Unload] Trying to free 7390.16 MB for cuda:0 with 0 models keep loaded ... Current free memory is 4164.87 MB ... Unload model JointTextEncoder Done.
[Memory Management] Target: KModel, Free GPU: 5914.48 MB, Model Require: 4897.05 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: -6.57 MB, CPU Swap Loaded (blocked method): 1139.06 MB, GPU Loaded: 3757.99 MB
Moving model(s) has taken 2.34 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [01:16<00:00,  2.54s/it]
[Unload] Trying to free 1296.42 MB for cuda:0 with 0 models keep loaded ... Current free memory is 2196.95 MB ... Done.
[Memory Management] Target: IntegratedAutoencoderKL, Free GPU: 2196.95 MB, Model Require: 159.56 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: 1013.40 MB, All loaded to GPU.
Moving model(s) has taken 0.09 seconds
Total progress: 100%|██████████████████████████████████████████████████████████████████| 30/30 [01:18<00:00,  2.60s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 30/30 [01:18<00:00,  2.56s/it]
```

### PC Features:
Windows 10
RX 580 8GB
Intel Xeon 1270 v3
25-30GB of free space on an ssd drive
Internet speed is more than 300mb/s
Installed tha latest version Git and Python 3.10.6

Actions that didn't help me:
Reinstalling (using git clone or zip) - no
Installing the original SD amd-gpu - no
Checking for viruses - no
Internet search - I didn't find the information I needed
Change the browser - no
Change the folder directory with SD - no
Create a new user and try it out - no
FULL reinstalling before Git and Python 3.10.6 - no
Lower the resolution, lower the prompt, change the model - it generates everything fine, but I need snowpony
Remove built-in extensions - no
Wait a few days and reinstall - no
Deleting venv folder - no
Deleting the pip folder - no
Write instead of --ditecrml --use-directml - no
Deleting all the latest installed programs before the SD worked - no
Reinstall the AMD driver - no
Reinstall the system - recently reinstalled
ReInstall HIP SDK libraries for RX580 and use ZLUDA - no
Put the recommended disk swap file - no

**Comment by TheFerumn** [comment]
`Error loading script: pa.py` refers to error of `sd-webui-prevent-artifact` extension. Never used it so i won't help. Anyway if it happens only with this one model it might be VAE decoder issue. Try to test some VAE models.
Also its PonyXL model so add negative prompt: `score_4,score_5,score_3,score_2,score_1`

Edit: I just checked on Civitai. This model doesn't have VAE included. This might be an issue

**Comment by TheFerumn** [comment]
Try this one as its suggested by author of model:
https://huggingface.co/madebyollin/sdxl-vae-fp16-fix

**Comment by Harbitos** [comment]
> Try this one as its suggested by author of model: https://huggingface.co/madebyollin/sdxl-vae-fp16-fix

Thank you very much, everything is working!
A question for you not to create an issue: how do I put Bnb-nf4 so that there is no error:
`Error named symbol not found at line 76 in file D:\a\bitsandbytes\bitsandbytes\csrc\ops.cu`

**Comment by lshqqytiger** [comment]
bitsandbytes is available only on NVIDIA cards. (real CUDA) #16
