### ISSUE TITLE
Was trying GGUF flux Schnell 

### ISSUE THREAD

**Issue by VeteranXT** [lshqqytiger/stable-diffusion-webui-amdgpu-forge#51]
I loaded ae, clip_i, T5 and GGUF Q4_K_S  it gave me this error.
`Traceback (most recent call last):
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\modules\txt2img.py", line 124, in txt2img_function
    processed = processing.process_images(p)
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\modules\processing.py", line 837, in process_images
    manage_model_and_prompt_cache(p)
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\modules\processing.py", line 805, in manage_model_and_prompt_cache
    p.sd_model, just_reloaded = forge_model_reload()
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\modules\sd_models.py", line 504, in forge_model_reload
    sd_model = forge_loader(state_dict, additional_state_dicts=additional_state_dicts)
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\backend\loader.py", line 287, in forge_loader
    component = load_huggingface_component(estimated_config, component_name, lib_name, cls_name, local_path, component_sd)
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\backend\loader.py", line 154, in load_huggingface_component
    load_state_dict(model, state_dict)
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\backend\state_dict.py", line 5, in load_state_dict
    missing, unexpected = model.load_state_dict(sd, strict=False)
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 2175, in load_state_dict
    load(self, state_dict)
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 2163, in load
    load(child, child_state_dict, child_prefix)  # noqa: F821
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 2157, in load
    module._load_from_state_dict(
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\backend\operations.py", line 136, in _load_from_state_dict
    self.weight = torch.nn.Parameter(state_dict[prefix + 'weight'].to(self.dummy))
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\nn\parameter.py", line 45, in __new__
    raise RuntimeError(f"Creating a Parameter from an instance of type {type(data).__name__} "
RuntimeError: Creating a Parameter from an instance of type ParameterGGUF requires that detach() returns an instance of the same type, but return type Tensor was found instead. To use the type as a Parameter, please correct the detach() semantics defined by its __torch_dispatch__() implementation.
Creating a Parameter from an instance of type ParameterGGUF requires that detach() returns an instance of the same type, but return type Tensor was found instead. To use the type as a Parameter, please correct the detach() semantics defined by its __torch_dispatch__() implementation.`

**Comment by VeteranXT** [comment]
I'm getting this error `size mismatch for transformer.text_model.final_layer_norm.bias: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([768]).`
