### ISSUE TITLE
28.11.2024 AnimateDiff problem: AttributeError: 'FakeInitialModel' object has no attribute 'is_sdxl'.

### ISSUE THREAD

**Issue by Harbitos** [lshqqytiger/stable-diffusion-webui-amdgpu-forge#57]
**Problem 1**: The extension is not displayed in the interface, even if it is enabled. I have already thrown in the "ldm" folder. 
Downloaded from here: https://github.com/CompVis/stable-diffusion.
![Screenshot_7](https://github.com/user-attachments/assets/bf4e0849-d6ac-46e4-8c18-401f360aa215)

With AnimateDiff standart: (https://github.com/guoyww/AnimateDiff)
```
*** Error loading script: animate.py
    Traceback (most recent call last):
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\extensions\AnimateDiff\scripts\animate.py", line 16, in <module>
        from animatediff.models.unet import UNet3DConditionModel
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\extensions\AnimateDiff\animatediff\models\unet.py", line 15, in <module>
        from diffusers.modeling_utils import ModelMixin
    ModuleNotFoundError: No module named 'diffusers.modeling_utils'
```

With AnimateDiff Forge version: (https://github.com/continue-revolution/sd-forge-animatediff)
```
*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff.py", line 10, in <module>
        from scripts.animatediff_infv2v import AnimateDiffInfV2V
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 5, in <module>
        from ldm_patched.modules.model_management import get_torch_device, soft_empty_cache
    ModuleNotFoundError: No module named 'ldm_patched'

---
*** Error loading script: animatediff_infotext.py
    Traceback (most recent call last):
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_infotext.py", line 6, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'

---
*** Error loading script: animatediff_infv2v.py
    Traceback (most recent call last):
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 5, in <module>
        from ldm_patched.modules.model_management import get_torch_device, soft_empty_cache
    ModuleNotFoundError: No module named 'ldm_patched'

---
*** Error loading script: animatediff_latent.py
    Traceback (most recent call last):
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_latent.py", line 10, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'

---
*** Error loading script: animatediff_mm.py
    Traceback (most recent call last):
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'

---
*** Error loading script: animatediff_output.py
    Traceback (most recent call last):
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_output.py", line 15, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'

---
*** Error loading script: animatediff_prompt.py
    Traceback (most recent call last):
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_prompt.py", line 7, in <module>
        from scripts.animatediff_infotext import write_params_txt
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_infotext.py", line 6, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'

---
*** Error loading script: animatediff_settings.py
    Traceback (most recent call last):
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_settings.py", line 4, in <module>
        from scripts.animatediff_ui import supported_save_formats
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'

---
*** Error loading script: animatediff_ui.py
    Traceback (most recent call last):
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'
```
    
**Problem 2**:
Even if I solved the problem, and I got the AnimateDiff tab, then the following problem: when I upload models for animateDiff from here: https://huggingface.co/guoyww/animatediff/tree/main (for example, `mm_sd_v14`, or `mm_sd_v15`, or `mm_sd_v15_v2`, or `mm_sdxl_v10_beta`) in `C:\Stable Diffusion\stable-diffusion-webui-amdgpu-forge\extensions\AnimateDiff\models`, then the extension leaves me with only one line and some kind of error in the console. 

An example of that one line:
![389229253-d701313b-b248-42fc-bf45-f23dc8d904e5](https://github.com/user-attachments/assets/415e9446-2e76-4a83-a773-b33ac2935640)

By the way, now I'm not sure where to put the models, AnimateDiff has already been updated: 
![Screenshot_6](https://github.com/user-attachments/assets/0f356f07-0b70-4d25-9f24-0225f83e1754)

**Comment by TheFerumn** [comment]
Haven't used it but when you check models from the huggingface link you can see different models and i guess the ones starting with mm in the name for example `mm_sd_v15.ckpt` will go into Motion_Module. Lora models obviously in MotionLora and i am not sure about the others.

**Comment by TheFerumn** [comment]
Forge version is broken and not updated. Looks like there is no point fixing it because this version launched without any errors for me but you have to test yourself if its working: https://github.com/continue-revolution/sd-webui-animatediff

**Comment by Harbitos** [comment]
> Forge version is broken and not updated. Looks like there is no point fixing it because this version launched without any errors for me but you have to test yourself if its working: https://github.com/continue-revolution/sd-webui-animatediff

I have another question for you: does "soft inpainting" work for you?

**Comment by TheFerumn** [comment]
Looks like model loading scripts are different than in A1111 WebUI. I would have to maybe check how other working similar extensions collect model parameters to fix it. Maybe i will do this in some boring day :D

**Comment by Harbitos** [comment]
> Looks like model loading scripts are different than in A1111 WebUI. I would have to maybe check how other working similar extensions collect model parameters to fix it. Maybe i will do this in some boring day :D

But how can I fix it?:

**Comment by TheFerumn** [comment]
> But how can I fix it? I don't know which models to put in, I just need to animate SDXL with lora PonyXL.

If you know nothing about python you won't fix it easily. I tried to fix it but after 1 problem another shows up. From my reasearch looks like Forge went into deep changes in August and Animatediff has trouble with checking model parameters. The extension code needs to be changed. I honestly don't know which version would be easier to edit Forge version or SD Web UI version. I don't know much how Stable Diffusion is built especially forge and i understand only basics of python code so it would take me a lot of time to figure it out. Maybe someone else can help or there are already other extensions which work similar way.

**Comment by Harbitos** [comment]
> > But how can I fix it? I don't know which models to put in, I just need to animate SDXL with lora PonyXL.
> 
> If you know nothing about python you won't fix it easily. I tried to fix it but after 1 problem another shows up. From my reasearch looks like Forge went into deep changes in August and Animatediff has trouble with checking model parameters. The extension code needs to be changed. I honestly don't know which version would be easier to edit Forge version or SD Web UI version. I don't know much how Stable Diffusion is built especially forge and i understand only basics of python code so it would take me a lot of time to figure it out. Maybe someone else can help or there are already other extensions which work similar way.

Does it work on your webui version? Or is this a complicated problem with all AMD's? Did it work for someone?

**Comment by TheFerumn** [comment]
I think you can forget about ComfyUI. If you really need this extension you might want to try with: https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu

**Comment by Harbitos** [comment]
> I think you can forget about ComfyUI. If you really need this extension you might want to try with: https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu

I noticed this: when I installed webui with _directml_ arguments, I still have a problem (one line), but if I remove _directml_ from the arguments, then my model is normally selected from _animateDiff_, but generation is **VERY slow**, even _512* 512_.
Of course, I did not wait for the results, but the generation began and progress appeared in the console. I waited for yes 15%.
I haven't tried _zluda_ yet.

Arguments:
`--skip-torch-cuda-test --theme dark --no-half --no-half-vae --upcast-sampling --precision full`

**Comment by Harbitos** [comment]
> I think you can forget about ComfyUI. If you really need this extension you might want to try with: https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu

What should I do? The problem has not been solved.

**Comment by dtroupe2** [comment]
I would be interested in seeing this work as well. I've been following this thread and have been having the same issues as you with this extension.

**Comment by Harbitos** [comment]
This seems to be a problem with SD Forge (amd/nvidia). Everything works fine on A1111 (on amd/nvidia).
I bought a new RTX 3060 12gb graphics card, so I didn't use any arguments.
I think I'll close this issue and open it on the AnimateDiff or SD Forge (nvidia) page.
