### ISSUE TITLE
04.12.2024 SD generates images for me from crystals (very often with the "Forge-Couple" extension). To solve the problem, I used the "prevent-artifact" extension and I get an error: Error loading script: pa.py

### ISSUE THREAD

**Issue by Harbitos** [lshqqytiger/stable-diffusion-webui-amdgpu-forge#59]
I sometimes get this when generating: (very more often with the "Forge Couple" extension enabled)
![2324234](https://github.com/user-attachments/assets/6aeb3faa-1271-430e-b2a8-db1e536e0e25)
It corrects, I don't understand how: whether to change the prompt somehow, or something else and it disappears or remove other loras...
Basically, changing the prompt helps.
In ComfyUI, I needed to kill the "Clip set last layer" that appeared every time...

In short: my friend recommended installing this extension https://github.com/hako-mikan/sd-webui-prevent-artifact
and put a check mark on:
![Screenshot_3](https://github.com/user-attachments/assets/f6eebafa-11d9-440d-bcc2-61cb498307e8)
He has to fix it on forge1111.

That's my problem itself, which is probably why this extension doesn't work:
(This error is always shown, even at startup)
```
*** Error loading script: pa.py
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui-amdgpu-forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\AI\stable-diffusion-webui-amdgpu-forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\AI\stable-diffusion-webui-amdgpu-forge\extensions\sd-webui-prevent-artifact\scripts\pa.py", line 55, in <module>
        sd_hijack_clip.FrozenCLIPEmbedderWithCustomWordsBase.process_tokens = process_tokens
    AttributeError: module 'modules.sd_hijack_clip' has no attribute 'FrozenCLIPEmbedderWithCustomWordsBase'

---
```
Arguments:
`--directml --upcast-sampling --theme dark --skip-version-check --opt-sub-quad-attention --disable-nan-check --always-low-vram --all-in-fp16`
I definitely have that check mark, I've already tried reinstalling the SD.

**Comment by TheFerumn** [comment]
I don't think you need this extension:

![image](https://github.com/user-attachments/assets/e56bbe04-9f99-462f-b99d-e42dec3a7321)

**Comment by Harbitos** [comment]
> I don't think you need this extension:
> 
> ![image](https://private-user-images.githubusercontent.com/178197881/393307637-e56bbe04-9f99-462f-b99d-e42dec3a7321.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MDM0NTgsIm5iZiI6MTczMzUwMzE1OCwicGF0aCI6Ii8xNzgxOTc4ODEvMzkzMzA3NjM3LWU1NmJiZTA0LTlmOTktNDYyZi1iOTlkLWU0MmRlYzNhNzMyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQxNjM5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzg0YmNlNTI0NDQ3NjdhMmY2NzU3YzViMTJiMTViNjdjMTVmNTk1MWQ2MTRjYjI3YjNiZTcyMzg0OWE0ODhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._YYkFcB3IsUGdR1aNdLkGrsHSZCiLWkdA796FV2F5Is)

I don't understand what "Emphasis" is, if I put something in the settings, will it fix the problem with broken generation for me?
![Screenshot_1](https://github.com/user-attachments/assets/730f00f2-1156-4d7a-926c-8a1ead351c64)

**Comment by Harbitos** [comment]
> I don't think you need this extension:

That is, if I check this box:
![Screenshot_2](https://github.com/user-attachments/assets/4e6bdc41-39c6-4bee-90bc-27d5aa843b35)
Will I always generate without problems?

**Comment by TheFerumn** [comment]
> Will I always generate without problems? After all, this is not a stable problem, it is checked only over time.

All that i am saying is this option apparently is doing the same as this extension which means you don't need extension. I don't know if that solves anything and there are tons of problems you can have while using Stable Diffusion so there is no magic button which will make sure you will always generate without problems

**Comment by CS1o** [comment]
What Type of models (checkpoints) did you used?
I discovered that these random "crystal" images mostly occur when you are using Pony based models + a prompt which contains word attention/emphasis like (word) or (word:1.2).
Removing the () and :1.2 fixed it then.

**Comment by Harbitos** [comment]
I bought an RTX 3060 12gb graphics card, so I had to close this issue.
